name: my_csmy
description: "Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^5.0.0
  flex_color_scheme: ^8.0.2 # Updated to the latest stable version
  device_info_plus: ^9.1.2
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true #添加 material支持
  assets:
  - assets/images/
  - assets/images/home.png
  fonts:
  - family: Customized # 字体名称
    fonts:
    - asset: assets/fonts/Customized-Regular.ttf   # 字体文件路径


  # Add your assets here.